# .slather.yml

xcodeproj: templateiOSApp/templateiOSApp.xcodeproj
workspace: templateiOSApp.xcworkspace
scheme: templateiOSApp
output_directory: ./testcoverage-reports

# source_directory: Pod/Classes
# binary_basename: templateiOSApp
# input_format: profdata
# coverage_service: coveralls
# ci_service: travis_pro
# ci_access_token: coveralltoken

ignore:
- Pods/*
