language:
    objective-c
osx_image:
    xcode9.2
xcode_project:
    templateiOSApp
before_install:
    - gem install bundler
install:
    bundle install
script:
    bundle exec fastlane test
after_success:
    - cd $TRAVIS_BUILD_DIR && slather
