language:
    objective-c
osx_image:
    xcode9.2
xcode_project:
    templateiOSApp
before_install:
    - gem install bundler
install:
    bundle install --without=documentation
script:
    bundle exec fastlane ios test
after_success:
    - slather
